"""`recount init`: a commented metrics.yml template from the dataset's columns.

Deterministic; reads only column names and types. Every inferred line is a starting
point the user is expected to edit: the template is the empty state and the tutorial.
"""

from __future__ import annotations

_TIME = ("DATE", "TIMESTAMP")
_NUMERIC = ("TINYINT", "SMALLINT", "INTEGER", "BIGINT", "HUGEINT", "UTINYINT", "USMALLINT",
            "UINTEGER", "UBIGINT", "UHUGEINT", "FLOAT", "DOUBLE", "DECIMAL")  # fmt: skip


def _kind(dtype: str) -> str:
    if dtype.startswith(_TIME):
        return "time"
    if dtype.startswith(_NUMERIC):
        return "numeric"
    if dtype.startswith("VARCHAR") or dtype.startswith("STRING"):
        return "text"
    return "other"


def _looks_like_id(name: str) -> bool:
    n = name.lower()
    return n == "id" or n.endswith("_id") or n.endswith("id") and len(n) <= 6


def _key(name: str) -> str:
    return "".join(c if c.isalnum() or c == "_" else "_" for c in name.lower()).strip("_") or "x"


def metrics_template(dataset: str, columns: dict[str, str], time_column: str | None = None) -> str:
    kinds = {c: _kind(t) for c, t in columns.items()}
    times = [c for c, k in kinds.items() if k == "time"]
    numerics = [c for c, k in kinds.items() if k == "numeric"]
    # id-like text columns are keys, not dimensions a report ranks or filters by
    texts = [c for c, k in kinds.items() if k == "text" and not _looks_like_id(c)]
    t = time_column or (times[0] if times else "<a DATE or TIMESTAMP column>")
    lines = [
        "# Recount semantic config, generated by `recount init` from the dataset's columns.",
        "# It defines what the report's words MEAN in this data. Recount verifies against these",
        "# definitions and nothing else: a wrong definition yields confidently wrong verdicts,",
        "# and a word not listed here is an UNVERIFIABLE (schema_gap), never a guess.",
        "#",
        "# Columns found: " + ", ".join(f"{c} ({columns[c]})" for c in columns),
        "",
        f"dataset: {dataset}",
        f"time_column: {t}"
        + ("" if times else "   # <- required: no DATE/TIMESTAMP column was found"),
        "tolerance_rule: half_ulp   # a stated number passes iff it correctly rounds the truth",
        "",
        "entities:",
    ]
    if texts:
        lines += [
            "  # One dimension per text column that reports name entities by (state, region,",
            "  # product...). aliases map the report's wording to the stored value; a subject",
            "  # the report uses that is not listed here abstains (schema_gap).",
        ]
        for c in texts:
            lines += [
                f"  {_key(c)}:",
                f"    column: {c}",
                "    aliases:",
                f'      # "Sao Paulo": SP     # <report wording>: <value stored in {c}>',
                "      {}",
            ]
    else:
        lines += ["  {}   # no text columns found; add a dimension when reports name entities"]
    lines += [
        "",
        "metrics:",
        "  # One metric per quantity reports state. agg: sum | count | avg | share.",
        "  # aliases: every way the report words this metric (matched as whole words,",
        "  # accent- and case-insensitive). round: decimals to round the aggregate to before",
        "  # comparing (pin it for SUM over floats). polarity: which direction is 'better';",
        "  # required for 'improved/worsened' and for rankings written as a quality",
        "  # ('led all states'); there is no default on purpose. min_rows: the rows a group",
        "  # needs to be in a ranking universe at all — without it a one-row group wins any",
        "  # average ranking, and a subject below it abstains (no_data), never FAILs.",
        "  row_count:",
        "    agg: count",
        "    aliases: [rows, records]   # <- rename to what a row IS (orders, visits, tickets)",
        "    polarity: higher_is_better",
        "    # min_rows: 30",
    ]
    for c in numerics:
        lines += [
            f"  total_{_key(c)}:",
            "    agg: sum",
            f"    column: {c}",
            f"    aliases: [total {c.replace('_', ' ')}]",
            "    round: 2",
            "    # polarity: higher_is_better",
            "    # min_rows: 30",
            f"  avg_{_key(c)}:",
            "    agg: avg",
            f"    column: {c}",
            f"    aliases: [average {c.replace('_', ' ')}]",
            "    min_rows: 30   # a mean over fewer rows than this does not enter a ranking",
            "    # polarity: lower_is_better",
        ]
    if texts:
        lines += [
            "  # share_of_rows:",
            "  #   agg: share            # an entity's row count over the period's row count",
            "  #   aliases: [share of all rows]",
            "  #   polarity: higher_is_better",
        ]
    return "\n".join(lines) + "\n"
